version: 2
jobs:
  # To test, we just build the code, run the tests, then create and upload
  # a coverage report.
  test-common: &test-common
    docker:
        - image: dwmkerr/node:10-imagemagick
    steps:
      - checkout
      - run: make test
      - run: npm run cov
      - run: bash <(curl -s https://codecov.io/bash)
      # Store test artifacts, useful for diagnosing failed tests.
      - store_artifacts:
          path: "src/init/test-images"
      - store_artifacts:
          path: "src/label/test-images"
      - store_artifacts:
          path: "src/resize/test-images"
  test-node10:
    <<: *test-common
    docker:
      - image: dwmkerr/node:10-imagemagick
  test-node12:
    <<: *test-common
    docker:
      - image: dwmkerr/node:12-imagemagick
  test-node14:
    <<: *test-common
    docker:
      - image: dwmkerr/node:14-imagemagick

workflows:
  version: 2
  build:
    jobs:
      - test-node10:
          # All branches, all tags.
          filters:
            tags:
              only: /.*/
      - test-node12:
          # All branches, all tags.
          filters:
            tags:
              only: /.*/
      - test-node14:
          # All branches, all tags.
          filters:
            tags:
              only: /.*/
